GenericExecuteSynth "echo \'$DATA\' | piper-tts -q -m /home/sky/.local/share/piper-voices/$VOICE -f - | pw-play -"

GenericCmdDependency "piper-tts"
GenericLanguage "en" "en_US" "utf-8"
GenericCharset "UTF-8"

AddVoice "en-US" "female1" "en_US-lessac-high.onnx"
AddVoice "en-US" "male1"   "en_US-ryan-high.onnx"
DefaultVoice "en_US-lessac-medium.onnx"

GenericDelimiters "|"
GenericMaxChunkLength 99999
